### ISSUE TITLE
something about babel-register

### ISSUE THREAD

**Issue by aweiu** [aleclarson/babel-register#1]
first,thank you for your 'babel-register'!it's very useful!it make my coding work more simple!
but,what do you think about that i use it in production environment?
i use it in nodejs,just want to know if it will make request not fast?
is it translate code once time or every time?

**Comment by aleclarson** [comment]
Sorry, I'm not the creator of `babel-register`.

But I found something that could help:

> 但请注意这种方法并不适合正式产品环境使用。

https://github.com/thejameskyle/babel-handbook/blob/master/translations/zh-Hans/user-handbook.md#toc-babel-register
